### ISSUE TITLE
'install' section is recommending general malpractice

### ISSUE THREAD

**Issue by Joonsey** [vsalli12/OVRDOZE#48]
install section in the README is advising one to install pip packages system-wide. This is not generally good practice as it can end up causing conflicts for a lot of linux distros. This is a nit-pick as you can assume that anyone operating a linux machine would naturally know how to deal with this but i believe it's worth considering having a low-hanging barrier to entry that ensures that this projects python modules does not install system-wide.

for instance you can advice the use of [venv](https://docs.python.org/3/library/venv.html), a built-in python module.
```
python -m venv venv
venv/bin/pip3 -r requirements.txt
```

**Comment by dille12** [comment]
Changed the readme so it consideres this
